site_name: Chuying's notebook
dev_addr: 127.0.0.1:3333
nav:
  - Home: index.md
  - Sketch:
      - Procreate: sketch/procreate/index.md
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji

# theme:
#   name: material
#   features:
#     - content.tabs.link