site_name: Chuying's notebook
dev_addr: 127.0.0.1:3333
nav:
  - Home: index.md
  - Architect:
      - AWS:
          - Cloud Practitioner: architect/aws/cp/index.md
          - Solution Architect Associate: architect/aws/saa/index.md
          - Solution Architect Professional: architect/aws/sap/index.md
      - IBM:
          - Security: architect/ibm/security.md
          - Storage: architect/ibm/storage.md
      - Guide from MemiLavi:
          - 1. Welcome: architect/memi/memi-1.md
          - 2. What is a Software Architect: architect/memi/memi-2.md
          - 3. The Architect's Mindset: architect/memi/memi-3.md
          - 4. The Architecture Process: architect/memi/memi-4.md
          - 5. Working with System Requirements: architect/memi/memi-5.md
          - 6. Types of Applications: architect/memi/memi-6.md
          - 7. Selecting Technology Stack: architect/memi/memi-7.md
          - 8. Meet the *-ilities: architect/memi/memi-8.md
          - 9. Components' Architecture: architect/memi/memi-9.md
          - 10. Design Patterns: architect/memi/memi-10.md
          - 11. System Architecture: architect/memi/memi-11.md
          - 12. Additional Considerations: architect/memi/memi-12.md
          - 13. Architecture Document: architect/memi/memi-13.md
          - 14. Case Study: architect/memi/memi-14.md
          - 15. Advanced Architecture Topics: architect/memi/memi-15.md
          - 16. Soft Skills: architect/memi/memi-16.md
      - Design Patterns (DP):
          - 1. Introduction: architect/design_patterns/1_intro.md
          - 2. Creational DP: architect/design_patterns/2_creational.md
          - 3. Structural DP: architect/design_patterns/3_structural.md
          - 4. Behavioral DP: architect/design_patterns/4_behavioral.md
  - Bash Script:
      - Basics: bash_script/index.md
      - Exercises: bash_script/exercises.md
  - Cloud:
      - Docker: cloud/docker/index.md
      - Helm: cloud/helm/helm-1.md
      - Kubernetes:
          - CKA:
              - Read before exam: cloud/k8s/cka/cka-0.md
              - cka-1: cloud/k8s/cka/cka-1.md
              - cka-2: cloud/k8s/cka/cka-2.md
              - cka-3: cloud/k8s/cka/cka-3.md
              - cka-4: cloud/k8s/cka/cka-4.md
              - cka-5: cloud/k8s/cka/cka-5.md
              - cka-6: cloud/k8s/cka/cka-6.md
              - cka-7: cloud/k8s/cka/cka-7.md
              - 8.Storage: cloud/k8s/cka/cka-8.md
              - cka-9: cloud/k8s/cka/cka-9.md
              - cka-10: cloud/k8s/cka/cka-10.md
              - cka-11: cloud/k8s/cka/cka-11.md
              - cka-12: cloud/k8s/cka/cka-12.md
              - cka-13: cloud/k8s/cka/cka-13.md
              - cka-14: cloud/k8s/cka/cka-14.md
              - cka-15: cloud/k8s/cka/cka-15.md
              - cka-16: cloud/k8s/cka/cka-16.md
          - CKAD:
              - Read before exam: cloud/k8s/ckad/ckad-0.md
              - 1.核心概念介绍: cloud/k8s/ckad/ckad-1.md
              - 2.配置: cloud/k8s/ckad/ckad-2.md
              - 3.多容器Pod: cloud/k8s/ckad/ckad-3.md
              - 4.容器状态监测: cloud/k8s/ckad/ckad-4.md
              - 5.Pod设计: cloud/k8s/ckad/ckad-5.md
              - 6.服务与网络: cloud/k8s/ckad/ckad-6.md
              - 7.容器数据的可持久化: cloud/k8s/ckad/ckad-7.md
              - 8.2021更新的考试内容: cloud/k8s/ckad/ckad-8.md
              - 其他: cloud/k8s/ckad/ckad-9.md
      - OpenShift:
          - App Deployment: cloud/openshift/deployment.md
          - Installation: cloud/openshift/installation.md
          - Internal Registry: cloud/openshift/internal_registry.md
          - Operator: cloud/openshift/operator.md
          - Pipeline: cloud/openshift/pipeline.md
          - DO288:
              - Deploying and Managing Applications: cloud/openshift/ex288/01_deploy_app.md
              - 2: cloud/openshift/ex288/02.md
              - 3: cloud/openshift/ex288/03.md
              - 4: cloud/openshift/ex288/04.md
              - 5: cloud/openshift/ex288/05.md
              - 6: cloud/openshift/ex288/06.md
              - 7: cloud/openshift/ex288/07.md
              - 8: cloud/openshift/ex288/08.md
          - DO280:
              - 1. Manifest & Kustomize: cloud/openshift/do280/01_manifest_kustimize.md
              - 2. OC Template & Helm Chart: cloud/openshift/do280/02_template_helm.md
              - 3. Authentication and Authorization: cloud/openshift/do280/03_auth.md
              - 4. Network Security: cloud/openshift/do280/04_network_security.md
              - 5. Expose SNI Application: cloud/openshift/do280/05_expose_sni_app.md
              - 6. Enable Developer Self-Service: cloud/openshift/do280/06_developer_self_service.md
              - 7. Kubernetes Operator: cloud/openshift/do280/07_kubernetes_operator.md
              - 8. Application Security: cloud/openshift/do280/08_application_security.md
              - 9. Openshift Updates: cloud/openshift/do280/09_oc_updates.md
              - 10: cloud/openshift/do280/10.md
  - Data Scientist:
      - Embedding: data_scientist/embedding.md
      - ElasticSearch: data_scientist/elastic_search.md
  - Design Thinking: design_thinking/index.md
  - DevOps:
      - Observability: dev_ops/observability/index.md
  - Ecommerce:
      - Wordpress: ecommerce/wordpress/index.md
  - Frontend:
      - CSS:
          - CSS In Depth: frontend/css/css-in-depth.md
          - Shape: frontend/css/shapes.md
      - CRA: frontend/cra.md
      - GSAP: frontend/gsap/index.md
      - JavaScript: frontend/js/index.md
      - Nginx: frontend/nginx/index.md
      - React:
          - Hooks: frontend/react/hooks.md
          - Basics: frontend/react/basics.md
          - Bugs: frontend/react/bugs.md
          - Oblivion: frontend/react/oblivion.md
          - Resources: frontend/react/resources.md
      - Web Design: frontend/web_design/index.md
  - ffmpeg: ffmpeg/index.md
  - IDEs:
      - VSCode: ide/vscode/index.md
  - Project Mgmt:
      - Agile: project_mgmt/agile/index.md
      - Git: project_mgmt/git/index.md
      - IBM PM: project_mgmt/ibm_internal/index.md
  - Python:
      - Grammars: python/grammars.md
      - FastAPI: python/fastapi/index.md
      - Oblivion: python/oblivion.md
      - Use dependencies: python/dependencies.md
      - Build Own Dependency: python/build_dependency.md
      - Virtual environment: python/virtual_env.md
  - Regex: regex/index.md
  - Sketch:
      - Procreate: sketch/procreate/index.md

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      title: Table of Contents
      permalink: True
      baselevel: 3
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji
#   - tables
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.prunes
extra_css:
  - stylesheets/extra.css
